# Generated by Django 2.2.3 on 2019-07-30 03:18

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.TextField()),
                ('real_name', models.TextField()),
                ('role', models.TextField(choices=[('Super Admin', '超级管理员'), ('Office Head', '办公室主任'), ('Dean', '院长'), ('Headmaster Office', '校办'), ('Secretary', '秘书'), ('Directory', '主任'), ('Applicant', '申请者'), ('Regular User', '普通用户')], default='Regular User')),
                ('department', models.TextField(choices=[('0', '计算机与信息科学学院')])),
                ('is_disabled', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'audit_sys_user',
                'ordering': ['id'],
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
