# Generated by Django 2.2.3 on 2019-08-21 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_sys_table',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('answer_type', models.TextField(choices=[('File', '文件'), ('Image', '图片'), ('Text', '单项输入'), ('Text Area', '矩阵输入')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Table')),
            ],
            options={
                'db_table': 'audit_sys_question',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(choices=[('0', '计算机与信息科学学院')])),
                ('position', models.TextField()),
                ('deadline', models.DateTimeField(null=True)),
                ('salary', models.TextField(null=True)),
                ('describe', models.TextField(null=True)),
                ('requirement', models.TextField(null=True)),
                ('status', models.TextField(choices=[('0', '已发布'), ('1', '已失效')], default='0')),
                ('account', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Table')),
            ],
            options={
                'db_table': 'audit_sys_job',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Question')),
            ],
            options={
                'db_table': 'audit_sys_answer',
            },
        ),
    ]
